### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/ytsub#22]
- [ ] update history when video is loaded from web share target 
- [ ] practice by typing
- [ ] proxy on gcp
- [ ] migrate to typescript
- [ ] vocabulary list based on script
  - save unfamiliar words in a sentence
  - show show as blank and ask user to fill
